# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jetsetter Tech
tagline:          'Code, Design, Travel'
description:      '<a href="https://www.jetsetter.com">Jetsetter</a> engineering, one post at a time.'
url:              http://tech.jetsetter.com
baseurl:          /

author:
  name:           'Jetsetter Engineering'
  url:            http://tech.jetsetter.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jetsetter
